
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: May 17 2022 23:29:26 PKT (May 17 2022 18:29:26 UTC)

// Verification Directory fv/azadi_soc_top 

module azadi_soc_top(clk_i, 
		     rst_ni, 
		     prog, 
		     boot_led, 
		     clks_per_bit,
     		     gpio_i, 
		     gpio_o, 
		     gpio_oe, 
		     uart_tx, 
		     uart_rx, 
		     pwm_o, pwm_o_2,
     		     pwm1_oe, 
		     pwm2_oe, 
		     ss_o, 
		     sclk_o, 
		     sd_o, 
		     sd_oe, 
		     sd_i, 
		     qsclk_o, 
		     qcs_o,
     		     qsd_i, 
		     qsd_o, 
		     qsd_oe, 
		     SE, 
		     TM, 
		     SI0, 
		     SO0, 
		     SI1, 
		     SO1);
  input clk_i, rst_ni, prog, uart_rx, sd_i, SE, TM, SI0, SI1;
  input [15:0] clks_per_bit;
  input [19:0] gpio_i;
  input [3:0] qsd_i;
  output boot_led, uart_tx, pwm_o, pwm_o_2, pwm1_oe, pwm2_oe, sclk_o,
       sd_o, sd_oe, qsclk_o, qcs_o, SO0, SO1;
  output [19:0] gpio_o, gpio_oe;
  output [1:0] ss_o;
  output [3:0] qsd_o, qsd_oe;
endmodule

